(cl:in-package ros_serial-msg)
(cl:export '(LINEAR-VAL
          LINEAR
          ANGULAR-VAL
          ANGULAR
          ODOMETER_X-VAL
          ODOMETER_X
          ODOMETER_Y-VAL
          ODOMETER_Y
          YAW_ANGLE-VAL
          YAW_ANGLE
          BATTERY_VOLTAGE-VAL
          BATTERY_VOLTAGE
          LEFT_ENCODER-VAL
          LEFT_ENCODER
          RIGHT_ENCODER-VAL
          RIGHT_ENCODER
          KEYSTATE-VAL
          KEYSTATE
          BUMP-VAL
          BUMP
          LEFT_OBS-VAL
          LEFT_OBS
          CENTRE_OBS-VAL
          CENTRE_OBS
          RIGHT_OBS-VAL
          RIGHT_OBS
          RIGHT_WALL-VAL
          RIGHT_WALL
          LEFT_NEC-VAL
          LEFT_NEC
          F_LEFT_NEC-VAL
          F_LEFT_NEC
          F_RIGHT_NEC-VAL
          F_RIGHT_NEC
          RIGHT_NEC-VAL
          RIGHT_NEC
          BRUSH_CURRENT-VAL
          BRUSH_CURRENT
          LEFT_WHEEL_CURRENT-VAL
          LEFT_WHEEL_CURRENT
          RIGHT_WHEEL_CURRENT-VAL
          RIGHT_WHEEL_CURRENT
          ROBOT_CURRENT-VAL
          ROBOT_CURRENT
          SYSTEM_TICKS-VAL
          SYSTEM_TICKS
))